### ISSUE TITLE
Importing `MemoizeJac` from SciPy raises a deprecation warning.

### ISSUE THREAD

**Issue by moorepants** [mechmotum/cyipopt#160]
See #157, but that didn't seem to help. See this issue on SciPy: https://github.com/scipy/scipy/issues/17572

**Comment by nrontsis** [comment]
What is the reason for using (the now seemingly private) [MemoizeJac](https://github.com/scipy/scipy/blob/684a519a327f76cdc4d9eee2a88d99437b90395f/scipy/optimize/_optimize.py#L57-L81)? Does caching function/Jacobian evaluations help noticeably in continuous optimisers like Ipopt?

**Comment by moorepants** [comment]
I don't know. I didn't write that code.

**Comment by moorepants** [comment]
My guess would be that has little to no effect because those functions would rarely be called with the same arguments.

**Comment by nrontsis** [comment]
Opened a PR to remove it: https://github.com/mechmotum/cyipopt/pull/161

**Comment by jhelgert** [comment]
> Does caching function/Jacobian evaluations help noticeably in continuous optimisers like Ipopt? I would assume it has no effect?

Depends on the optimization problem. 

For instance, for an objective function that contains some expensive-to-evaluate expression `tmp`  which depends on the optimization variables and arises in the gradient as well, you can avoid duplicated computations of `tmp` by evaluating the objective and the gradient with a single function call and using the `jac=True` option. Here, the effect would be huge because you save one expensive calculation per iteration. An illustrative example of `tmp` might be an inverse matrix that depends on the optimization variable.

IIRC, the main intention for adding this feature to cyipopt's scipy interface was because it's in scipy.optimize.minimize too.

**Comment by moorepants** [comment]
Yes, I think we should leave it in. After watching the discussion over at SciPy I think we will just have to import from `scipy.optimize._optimize` and risk breaking changes or we can copy MemoizeJac into this library (and the license of SciPy).
