### ISSUE TITLE
Remove .github/workflows/test.yml

### ISSUE THREAD

**Issue by moorepants** [mechmotum/cyipopt#187]
We have tests.yml which covers a matrix of os, python, and ipopt versions. There is also test.yml that seems to cover one instance of that matrix and is redundant. I'm not sure why we have test.yml. I think it probably should be removed.

**Comment by brocksam** [comment]
The original reasons for this was that `test.yml` (with its single OS, Python version, and IPOPT version combination) is triggered on push and PR to all branches, while `tests.yml` (with the full matrix) is only triggered on PR to the master branch. The reason I did this in the first place no longer really feels valid: parallel jobs were limited to two at a time and the Windows jobs took ~15 mins, so if a test was failing because of a general mistake it could take a few hours to get that feedback via PR. 

I think we can delete `test.yml` and change the `on` conditions in `tests.yml` to be just `on: [push, pull_request]`.
