### ISSUE TITLE
Package broken (minimal example won't work)

### ISSUE THREAD

**Issue by mayou36** [mechmotum/cyipopt#92]
Installing the package with anaconda and executing the minimal example of the README doesn't work. Somehow the namespace looks completely different.

```
from scipy.optimize import rosen, rosen_der
from cyipopt import minimize_ipopt
x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize_ipopt(rosen, x0, jac=rosen_der)
print(res)
```

does not find `minimize_ipopt`

**Comment by brocksam** [comment]
I think this is because the README on the package homepage corresponds to the `master` branch of CyIpopt which is currently version 1.0.0.dev0. Whereas you will probably have installed version 0.3.0 from conda-forge. Version 1.x.x will change a number of things to do with the packages API. Mainly the user of will import `cyipopt` whereas in version 0.x.x the user imports `ipopt`. This is to avoid confusion between this package and the NLP solver, Ipopt, that it wraps.

Try browsing the repo at the point of release of version 0.3.0 (https://github.com/mechmotum/cyipopt/tree/579dac9f1b6d83b1f1515c67223e3148b5604675). You should find that the README there matches the API of what you have installed. There are also online docs which correspond to version 0.x.x (https://pythonhosted.org/ipopt/tutorial.html#getting-started).

**Comment by moorepants** [comment]
Yes, you should install the development version if you want to run examples form the tip of of the master branch. I'm closing this issue. Please reopen if we're mistaken.

@brocksam We should make a checklist of things to finalize a 1.0 release.
